import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { useState } from 'react'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false)


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Template: with - tailwindcss, nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-zinc-300'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-godofwar'>JCesar Dev</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill 
              onClick={() => setDarkMode(!darkMode)} 
              className='cursor-pointer text-2xl'/></li>
              <li> <a href="#" className='bg-gradient-to-r from-slate-400 to-slate-600 text-white px-4 py-2 rounded-md ml-8 font-black'> Sobre</a></li>
            </ul>
          </nav>

        <div className='h-screen flex justify-center items-center flex-col '>
          
            <h2 className='text-2xl'>Template with Nextjs and Tailwindcss</h2>
            <h3 className='text-xl'>Stay free to clone and editying</h3>
          
        </div>

        </section>
      </main>
    </div>
  )
}
